// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxw9HSxycfNIioPy7trKkHbv49HVJ7Tdw',
    appId: '1:1097355670357:android:67393830463f0a2688b5dc',
    messagingSenderId: '1097355670357',
    projectId: 'geomaster-22',
    databaseURL: 'https://geomaster-22-default-rtdb.firebaseio.com',
    storageBucket: 'geomaster-22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDdVYORvb3t3YWdC1o5YA12aNS0zSdQWI',
    appId: '1:1097355670357:ios:a3142fb22a04b2ac88b5dc',
    messagingSenderId: '1097355670357',
    projectId: 'geomaster-22',
    databaseURL: 'https://geomaster-22-default-rtdb.firebaseio.com',
    storageBucket: 'geomaster-22.appspot.com',
    iosClientId: '1097355670357-m5cc0ue1ipehe7etdfqfvf15thaj49p4.apps.googleusercontent.com',
    iosBundleId: 'com.geo.geomaster',
  );
}
